fix docs generation
Fixes error:

```
  File "/LSP/plugin/core/views.py", line 31, in <module>
    _baseflags = sublime.DRAW_NO_FILL | sublime.DRAW_NO_OUTLINE | sublime.DRAW_EMPTY_AS_OVERWRITE
TypeError: unsupported operand type(s) for |: 'DRAW_NO_FILL' and 'DRAW_NO_OUTLINE'
```

on `make build`.

Sphinx is not able to properly handle types for auto-stubbed sublime
module and does not support stub files so hack around it by changing
the failing constants to 0.

Fixes #76